site_name: Elon
site_url: https://faketwitter.github.io/elon
repo_url: https://github.com/FakeTwitter/elon
theme: readthedocs
copyright: <b>A Fake Twitter Original Production</b><br><a href="http://faketwitter.github.io/">Fake Twitter OSS</a> | <a href="http://techblog.faketwitter.com/">Tech Blog</a> | <a href="https://faketwitter.com/Fake TwitterOSS">Fake Twitter @Fake TwitterOSS</a> | <a href="https://jobs.faketwitter.com">Jobs</a>
pages:
  - Home: index.md
  - How to deploy: How-to-deploy.md
  - Configuration file format: Configuration-file-format.md
  - Configuring behavior via Sysbreaker: Configuring-behavior-via-sysbreaker.md
  - Termination behaior: Termination-behavior.md
  - Running locally: Running-locally.md
  - Plugins:
      - Home: plugins/index.md
      - Decryptor: plugins/Decryptor.md
      - Error counter: plugins/Error-counter.md
      - Outage checker: plugins/Outage-checker.md
      - Tracker: plugins/Tracker.md
      - Constrainer: plugins/Constrainer.md
  - Development:
      - Running tests: dev/Running-tests.md
      - Vendoring dependencies: dev/Vendoring-dependencies.md
